
# html lang
language: en

# main menu navigation
menu:
  Home: /
  Archives: /archives
  Tags: /tag
  Github: https://github.com/Jvaeyhcd
  # About: /about

# stylesheets loaded in the <head>
stylesheets:
- /css/dexo.css
- /css/custom.css
- /css/post.css
- /css/page.css
- /css/layout.css
- /css/font-awesome.min.css

# scripts loaded in the end of the body
scripts:
- /js/dexo.js
- /js/helper.js

# Disqus
disqus_shortname: jvaeyhcd

# Facebook
facebook_name: Jvaeyhcd

# Github
github_name: Jvaeyhcd

# Twritter
twitter_name: jvaeyhcd

#gitalk settings
gitalk:
  enable: true #用来做启用判断可以不用
  owner: Jvaeyhcd
  repo: jvaeyhcd.github.io #储存评论issue的github仓库名
  admin: Jvaeyhcd
  clientID: 29d526fe1e0f29d6b28c
  clientSecret: 1e5c674f3cbce0ba7d19045138d69ef800d5bd21

google_analytics: 

# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true