# Blog info
blog_name: Jvaeyhcd
slogan: You're uinique, nothing can replace you.
url: http://www.Jvaeyhcd.com

# Github info
social:
   Weibo: http://weibo.com/javeyhcd
   GitHub: https://github.com/Jvaeyhcd